name: Esegui Script Richiami 2 Volte al Giorno

on:
  schedule:
    - cron: '17 9,18 * * *'
  workflow_dispatch:

# Dà al bot il permesso esplicito di scrivere e salvare i file nel repository
permissions:
  contents: write

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Copia i file del repository
        uses: actions/checkout@v4

      - name: Installa Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa le librerie
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui lo script Python
        run: python scarica_richiami.py

      - name: Salva i dati sul repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Aggiornamento automatico dei dati" || echo "Nessuna modifica da salvare"
          git push
