name: Aggiorna Allette RASFF Italia

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  aggiorna-dati:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa le librerie necessarie
        run: pip install requests

      - name: Esegui lo script Python
        run: python importjson.py

      - name: Salva il file JSON aggiornato nel repository
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add avvisi_richiami_osa.json
          
          if git diff --staged --quiet; then
            echo "Nessun nuovo dato da aggiornare. Evito il push."
          else
            git commit -m "🤖 Aggiornamento automatico allerte RASFF Italia"
            git pull origin main --rebase
            git push
          fi
